---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : my_hooligan
production_url : http://www.davedoesdev.com

posts:
  permalink: /:categories/:title/
  summary_lines: 10
  latest: 10

pages:
  permalink: 'pretty'
