title : Dave Does Dev
tagline:
author :
  name : David Halls
  email : dahalls@gmail.com
  github : davedoesdev
  twitter : davedoesdev
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
