title : Dave Does Dev
tagline:
author :
  name : David Halls
  email : dave@davedoesdev.com
  github : davedoesdev
  twitter : davedoesdev
  linkedin: dhalls

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
