name: compile

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install gems
        run: bundle install --full-index

      - name: Compile
        run: ./compile.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: compiled

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: compiled
