name: compile

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install gems
        run: |
          bundle install || bundle update ruhoh
          gem list
          find . -name ruhoh-2.6
          sudo find / -name ruhoh-2.6

      - name: Compile
        run: ./compile.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled
          path: compiled

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: compiled
